# .pre-commit-config.yaml

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: [--fix]
        files: ".*\\.py"
      - id: ruff-format
        files: ".*\\.py"

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
        files: ".*\\.ipynb"
        args: [
          "--ignore=E402,F821,I001"
        ]
      - id: nbqa-isort
        files: ".*\\.ipynb"
