# pyproject.toml

# --- PROJECT DEFINITION ---
# This is the main configuration for installable package.
[project]
name = "scholar-agent"
version = "0.1.0"
description = "A multi-agent AI system for building and querying a scientific knowledge graph."
authors = [
    {name = "Shilpa Musale", email = "shilpa.musale02@gmail.com"},
]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    # Core AI & LangChain
    "langchain",
    "langchain-google-genai",
    "langgraph",
    "sentence-transformers",
    "ragas==0.1.7",
    "flashrank",

    # Vector Store
    "chromadb",

    # API Framework
    "fastapi",
    "uvicorn",

    # Data Handling & Notebooks
    "pandas",
    "numpy",
    "jupyterlab",
    "pypdf",
    "datasets",
    "arxiv",
    "requests", # For Semantic Scholar API

    # Graph Database
    "neo4j",

    # Utilities & Dev Tools
    "python-dotenv",
    "tqdm",
    "ruff",
    "nbqa",
    "isort",

    # Testing & Code Quality
    "pytest",
    "pre-commit",

    # Visualization
    "pygraphviz",

    #Python keyphrase extraction
    "pke @ git+https://github.com/boudinfl/pke.git",
    "spacy"

]

# --- BUILD SYSTEM CONFIGURATION ---
# This tells the installer how to build project.
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# --- SETuptools CONFIGURATION ---
[tool.setuptools.packages.find]
where = ["src"]

# --- LINTER & FORMATTER CONFIGURATION ---
[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]

[tool.nbqa.config]
# Ignore "imports not at top of file" only for notebooks
ruff = ["--extend-ignore=E402"]

[tool.nbqa.addopts]
# Auto-fix issues in notebooks where possible
ruff = ["--fix"]
isort = []

[tool.pytest.ini_options]
dotenv_files = [".env"]