# Copyright 2025 Shilpa Musale
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
fetch_s2_metadata.py: Enriches paper metadata using the Semantic Scholar API.

This module takes the initial list of papers generated by the arXiv fetcher and
enriches each paper with detailed, structured data from the Semantic Scholar (S2)
Academic Graph API. It is a critical step for acquiring high-quality citation
data, which is used to build the `CITES` relationships in the knowledge graph.

The script is designed for robustness and resilience:
- It uses an authenticated API key for reliable access.
- It implements a retry mechanism with exponential backoff to gracefully handle
  API rate-limiting errors (HTTP 429).
- It handles cases where a paper is not found in the S2 database (HTTP 404).

The output is `data/processed/s2_metadata.json`, a dictionary mapping a clean
arXiv ID to the rich metadata object returned by the S2 API.
"""

# src/data_processing/fetch_s2_metadata.py

import json
import os
import re
import time
from typing import Any

import requests
from dotenv import load_dotenv
from tqdm import tqdm

import configs.settings as settings
from src.utils.logging_config import setup_logging

logger = setup_logging(__name__, "fetch_s2_metadata")


def clean_arxiv_id(arxiv_id: str) -> str:
    """Removes the version number from an arXiv ID."""
    return re.sub(r"v\d+$", "", arxiv_id)


def fetch_paper_metadata(arxiv_id: str, api_key: str) -> dict[str, Any] | None:
    """
    Fetches detailed metadata for a single paper from Semantic Scholar,
    implementing retries with exponential backoff for rate limiting.
    """
    clean_id = clean_arxiv_id(arxiv_id)
    url = f"{settings.S2_API_URL}/paper/arXiv:{clean_id}"
    params = {"fields": settings.S2_API_FIELDS}
    headers = {"x-api-key": api_key}

    max_retries = 3
    base_backoff = 5

    for attempt in range(max_retries):
        try:
            response = requests.get(url, params=params, headers=headers)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.HTTPError as e:
            if e.response.status_code == 429:  # Rate limit error
                wait_time = base_backoff * (2**attempt)
                logger.warning(
                    f"Rate limit hit for arXiv:{clean_id} on attempt "
                    f"{attempt + 1}. Waiting for {wait_time} seconds."
                )
                time.sleep(wait_time)
                continue  # Retry the loop
            elif e.response.status_code == 404:
                logger.warning(f"Paper arXiv:{clean_id} not found on S2.")
                return None
            else:
                logger.error(f"HTTP Error for arXiv:{clean_id}: {e}")
                return None
        except requests.exceptions.RequestException as e:
            logger.error(f"Request failed for arXiv:{clean_id}: {e}")
            return None

    logger.error(
        f"Failed to fetch metadata for arXiv:{clean_id} after {max_retries} attempts."
    )
    return None


def fetch_all_metadata() -> None:
    """
    Main function to fetch metadata for all papers and save it as a dictionary.
    """
    load_dotenv()
    api_key = os.getenv("S2_API_KEY")
    if not api_key:
        raise ValueError("S2_API_KEY not found in .env file.")

    input_path = settings.PROCESSED_DATA_PATH / "arxiv_metadata.json"
    output_path = settings.PROCESSED_DATA_PATH / "s2_metadata.json"

    try:
        with open(input_path) as f:
            initial_papers = json.load(f)
    except FileNotFoundError:
        logger.error(f"Input file not found: {input_path}. Please run 'make'.")
        return

    logger.info(f"Fetching S2 metadata for {len(initial_papers)} papers...")

    enriched_papers_map: dict[str, Any] = {}
    for paper in tqdm(initial_papers, desc="Fetching S2 Data"):
        arxiv_id = paper.get("arxiv_id")
        if not arxiv_id:
            continue

        metadata = fetch_paper_metadata(arxiv_id, api_key)
        if metadata:
            enriched_papers_map[clean_arxiv_id(arxiv_id)] = metadata

        time.sleep(1)

    with open(output_path, "w") as f:
        json.dump(enriched_papers_map, f, indent=2)

    logger.info(
        f"Successfully saved S2 metadata for {len(enriched_papers_map)} "
        f"papers to {output_path}"
    )


if __name__ == "__main__":
    fetch_all_metadata()
